# Generated by Django 4.2.2 on 2023-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0003_delete_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=500)),
                ("team2", models.CharField(max_length=500)),
                ("players_team1", models.TextField()),
                ("players_team2", models.TextField()),
            ],
        ),
    ]
