# Generated by Django 4.2.2 on 2023-06-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0006_delete_players"),
    ]

    operations = [
        migrations.CreateModel(
            name="Players",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=4)),
                ("team", models.TextField()),
                ("role", models.TextField(default="role")),
            ],
        ),
    ]
