# Generated by Django 4.2.2 on 2023-06-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0007_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="image",
            field=models.TextField(default="image"),
        ),
        migrations.AddField(
            model_name="players",
            name="nation",
            field=models.TextField(default="nation"),
        ),
        migrations.AlterField(
            model_name="trades",
            name="players_team1",
            field=models.TextField(default="players_team1", null=True),
        ),
        migrations.AlterField(
            model_name="trades",
            name="players_team2",
            field=models.TextField(default="players_team2", null=True),
        ),
    ]
