# Generated by Django 4.2.2 on 2023-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0008_players_image_players_nation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trades_Compensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=500)),
                ("team2", models.CharField(max_length=500)),
                ("players_team1", models.TextField(default="players_team1", null=True)),
                ("compensation", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(default="Description")),
            ],
        ),
        migrations.RenameModel(
            old_name="Trades",
            new_name="Trades_Players",
        ),
    ]
