# Generated by Django 4.2.2 on 2023-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machine", "0010_alter_trades_compensation_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="trades_compensation",
            name="title",
            field=models.TextField(default="Description"),
        ),
        migrations.AddField(
            model_name="trades_players",
            name="title",
            field=models.TextField(default="Description"),
        ),
    ]
